POST http://localhost:3000/api/courses/add/5e6d4fc149864f1094ab8ef0 HTTP/2
Accept: application/json
Content-Type: multipart/form-data; boundary=----WebKitFormBoundary7MA4YWxkTrZu0gW

------WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="course"

{   "title": "mongoDB", 
    "category": "nosql",
    "level": "intermediate",
    "prerequisites": "none",
    "image": "",
    "topic": "mongodb nosql database",
    "description": "use mongoDB ",
    "published": true,
    "lectures": []
}
------WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="mongodb_logo"; filename="../testFiles/mongodb_logo.jpg"
Content-Type: image/jpeg

< ./testFiles/mongodb_logo.jpg
------WebKitFormBoundary7MA4YWxkTrZu0gW--

--------------------------------------------------
