# Test FIND ALL
GET http://localhost:3000/index

###
# Test FIND all courses BY catagory
GET http://localhost:3000/index/IT

###
# Test FIND ONE
GET http://localhost:3000/index/It/5e6e27aad33e6f2d2810afe9
